all:
	gcc -Werror -Wpedantic -Wall -Wextra main.c -o main
	gcc -Werror -Wpedantic -Wall -Wextra test.c -o test
	gcc -Werror -Wpedantic -Wall -Wextra test_no_root.c -o test_no_root

clean:
	rm main
	rm test
	rm test_no_root